module.exports = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  safelist: [
    "grid-rows-2",
    "grid-cols-2",
    "grid-rows-9",
    "grid-cols-9",
    "grid-rows-8",
    "grid-cols-8",
    "grid-rows-6",
    "grid-cols-6",
    "grid-rows-4",
    "grid-cols-4",
    "grid-rows-3",
    "grid-cols-3",
    "h-32",
    "h-24",
    "h-16",
    "h-8",
    "w-32",
    "w-24",
    "w-16",
    "w-8",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
